apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
data:
  APP_NAME: test-app
  APP_ENV: production
  APP_DEBUG: "true"
  APP_URL: http://localhost:8080
  LOG_CHANNEL: stack
  LOG_LEVEL: debug
  DB_CONNECTION: mysql
  DB_HOST: mysql-main
  DB_PORT: "3306"
  DB_DATABASE: application_main
  DB_USERNAME: main
  BROADCAST_DRIVER: log
  CACHE_DRIVER: redis
  QUEUE_CONNECTION: sync
  SESSION_DRIVER: redis
  SESSION_LIFETIME: "120"
  REDIS_HOST: redis-master
  REDIS_PORT: "6379"
  REDIS_CLIENT: "predis"
