apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-application-main-service
  name: web-application-main-service
spec:
  type: NodePort
  selector:
    app: web-application-main
  ports:
    - name: targetport
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30009
