apiVersion: v1
kind: Secret
metadata:
  name: application-secret
type: Opaque
data:
  REDIS_PASSWORD: cmRzaGFyZFBhc3MxMjM=
  DB_PASSWORD: c3FsaGFyZFBhc3MxMjM=
  APP_KEY: YmFzZTY0OjdtT2JDOVpmU2JRaGRiNnJsdlJNdGJOYzF4NVdtUjR1YnRKNjNDVy9pdmc9Cg==
